### PR TITLE
[INFS-4028] Add new ALB auth error Enum

### PR DESCRIPTION
**Pull request by bahram-cdt**
Adding a simple ALB error Enum

Reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html#authentication-flow

### CODE REVIEW

**Comment by bahram-cdt** [comment]
@dpetzold can you please check this out ? It is blocking us from parsing ALB parsing rules

**Comment by dpetzold** [comment]
> @dpetzold can you please check this out ? It is blocking us from parsing ALB logs

Hi @bahram-cdt . Thank you for submitting this. Can you include a test case or comment here with the line is breaking and I will release a new version.

**Comment by bahram-cdt** [comment]
Hi @dpetzold , 
Thanks for your reply and being available. 

I have pushed the unit test case for "AuthInvalidAWSALBAuthNonce" error

**Comment by bahram-cdt** [comment]
BTW, I might not be available to reply to your comments, my colleague will pick it up in case follow-ups needed: 
[@pkoltermann](https://github.com/pkoltermann)

**Comment by dpetzold** [comment]
@bahram-cdt thank you. I pushed a new release to pypi 2.4.0.

**Pull request merged**
